// apps/angular/src/app/app.component.ts
import { Component, effect, inject, OnInit, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from './auth.service';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, ReactiveFormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  session = this.authService.session;
  registerMode = signal(false);

  ngOnInit() {
    this.authService.getSession();
  }

  constructor() {
    effect(() => {
      if (this.registerMode()) {
        this.loginForm.reset();
      } else {
        this.registerForm.reset();
      }
    });
  }

  loginForm = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]],
  });

  registerForm = this.fb.group({
    name: ['', [Validators.required]],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]],
  });

  onSubmit() {
    if (this.registerMode()) {
      if (this.registerForm.valid) {
        this.authService.signUp(
          this.registerForm.value.name!,
          this.registerForm.value.email!,
          this.registerForm.value.password!,
        );
      }
    } else if (this.loginForm.valid) {
      this.authService.signIn(this.loginForm.value.email!, this.loginForm.value.password!);
    }
  }

  signOut() {
    this.authService.signOut();
  }

  toggleRegisterMode() {
    this.registerMode.set(!this.registerMode());
  }
}

<main class="main">
  <div class="content">
    @if (session().error) {
      <p>Error: {{ session().error?.message }}</p>
    }

    @if (session().isPending) {
      <p>Loading...</p>
    } @else if (session().data.user) {
      <p>Welcome, {{ session().data.user?.name }}!</p>
      <button (click)="signOut()">Sign out</button>
    } @else {
      <form [formGroup]="registerMode() ? registerForm : loginForm" (ngSubmit)="onSubmit()">
        <div>
          @if (registerMode()) {
            <input id="name" type="text" placeholder="Name" formControlName="name" />
            <label for="name">Name</label>
          }
        </div>

        <div>
          <input id="email" type="email" placeholder="Email" formControlName="email" />
          <label for="email">Email</label>
          @if (
            registerMode()
              ? registerForm.controls.email.invalid && registerForm.controls.email.touched
              : loginForm.controls.email.invalid && loginForm.controls.email.touched
          ) {
            @if (
              registerMode()
                ? registerForm.controls.email.errors?.['required']
                : loginForm.controls.email.errors?.['required']
            ) {
              <p>Email is required</p>
            }
            @if (
              registerMode()
                ? registerForm.controls.email.errors?.['email']
                : loginForm.controls.email.errors?.['email']
            ) {
              <p>Invalid email</p>
            }
          }
        </div>
        <div>
          <input id="password" type="password" placeholder="Password" formControlName="password" />
          <label for="password">Password</label>
          @if (
            registerMode()
              ? registerForm.controls.password.invalid && registerForm.controls.password.touched
              : loginForm.controls.password.invalid && loginForm.controls.password.touched
          ) {
            @if (
              registerMode()
                ? registerForm.controls.password.errors?.['required']
                : loginForm.controls.password.errors?.['required']
            ) {
              <p>Password is required</p>
            }
          }
        </div>

        <button type="submit">
          @if (registerMode()) {
            Sign up
          } @else {
            Sign in
          }
        </button>
      </form>

      <div>
        @if (registerMode()) {
          Already have an account? <button (click)="toggleRegisterMode()">Sign in</button>
        } @else {
          Don't have an account? <button (click)="toggleRegisterMode()">Sign up</button>
        }
      </div>
    }
  </div>
</main>

<router-outlet />

// apps/web/src/App.tsx
import { useState } from 'react';
import './App.css';

import { useSession, signUp, signIn, signOut } from './lib/auth-client';

function App() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [registerMode, setRegisterMode] = useState(false);

  const { data } = useSession();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (registerMode) {
      await signUp.email(
        { name, email, password },
        {
          redirectTo: '/',
          onRequest: () => {
            // Loading...
          },
          onSuccess: (data) => {
            console.log('success', data);
          },
          onError: (error) => {
            console.error(error);
          },
        },
      );
    } else {
      await signIn.email({ email, password });
    }
  };
  return (
    <div>
      {data?.user ? (
        <div>
          <h1>Welcome {data.user.name}</h1>
          <button type="button" onClick={() => signOut()}>
            Sign out
          </button>
        </div>
      ) : (
        <form onSubmit={handleSubmit}>
          {registerMode ? (
            <>
              <div>
                <label htmlFor="name">Name</label>
                <input type="text" id="name" value={name} onChange={(e) => setName(e.target.value)} required />
              </div>
              <div>
                <label htmlFor="email">Email</label>
                <input type="email" id="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
              </div>
              <div>
                <label htmlFor="password">Password</label>
                <input
                  type="password"
                  id="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <button type="submit">Sign up</button>
            </>
          ) : (
            <>
              <div>
                <label htmlFor="email">Email</label>
                <input type="email" id="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
              </div>
              <div>
                <label htmlFor="password">Password</label>
                <input
                  type="password"
                  id="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <button type="submit">Sign in</button>
            </>
          )}

          <div>
            <span>
              {registerMode ? 'Already have an account? ' : "Don't have an account? "}
              <button type="button" onClick={() => setRegisterMode(!registerMode)}>
                {registerMode ? 'Sign in' : 'Sign up'}
              </button>
            </span>
          </div>
        </form>
      )}
    </div>
  );
}

export default App;
